### ISSUE TITLE
Generating schema for nested objects

### ISSUE THREAD

**Issue by gavinwahl** [yuga/jsonschema-gen#5]
Hi,

If I have a type like this:

``` haskell
data Foo = Foo Bar deriving (Generic)
data Bar = Bar Int deriving (Generic)

instance JSONSchemaGen Foo
instance JSONSchemaGen Bar
```

When I run `generate (Proxy :: Proxy Foo)`, I only get Foo in the schema, not Bar:

``` json
{
    "items": [
        {
            "$ref": "Main.Bar"
        }
    ],
    "$schema": "http://json-schema.org/draft-04/schema#",
    "id": "Main.Foo",
    "title": "Main.Foo",
    "type": "array"
}
```

How can I generate the schema for all the types involved, not just the top level one?

**Comment by yuga** [comment]
Currently <code>generate (Proxy :: Proxy Foo)</code> just generates a schema of Foo. You need to use <code>generate (Proxy :: Proxy Bar)</code> for generating a schema of Bar.

jsonschema-gen is designed for use with multiple schema files where a json schema of each data type is defined in an independent schema file. Nested data type, like Bar used in Foo, is referenced by its id specified in <code>$ref</code> attribute.

Whether this design goes well or not, it depends on tool set for json and jsonschema.
